name: ⛔️ Revoke SSH key authorization policy
on:
  schedule:
    - cron: 0,59 * * * * # runs every 59 mins
  workflow_dispatch:

jobs:
  revoke-ssh-keys:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
        owner: joshjohanning-org-saml # ${{ github.repository_owner }}
    - name: Check and Revoke SSH keys
      uses: joshjohanning/revoke-github-ssh-key-sso-authorization@main
      with:
        organization: joshjohanning-org-saml # ${{ github.repository_owner }}
        github-token: ${{ steps.app-token.outputs.token }} # could also use PAT with `admin:org` scope
        dry-run: false # change to true to not revoke any SSH key
        create-issue: true # change to true to create an issue and assign to the user whose SSH key is being revoked (can't be used with dry-run)
        issue-repo: ${{ github.repository }} # if create-issue is true, repo to create the issue in
